# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('numPlots', models.IntegerField(default=0)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
